import { Inter } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import Loading from "./loading"
import { Toaster } from 'sonner';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "EDUsync",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

      <html lang="en">
        <Suspense fallback={<Loading />} >
        <body className={inter.className}>
          {children}
          <Toaster richColors position="top-right" />
          </body>
          </Suspense>
      </html>

  );
}
